#!/bin/bash

files="inputs/small/*.in"
regex="^inputs/(.*)\.in$"

commands=""
for file in $files; do
        if [[ $file =~ $regex ]]
        then
                echo -e ${BASH_REMATCH[1]} ${file}
                if [ ! -f "$outputs/${BASH_REMATCH[1]}.out" ]; then
                        commands+="./a.out ${BASH_REMATCH[1]} < $file 2>/dev/null\n"
                fi
        fi
done
echo -e $commands
# echo -e $commands | parallel -j8 -k

